
import __ASTRO_IMAGE_IMPORT_ZuwFOt from "../../assets/images/blog.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F02-blog.json";
import __ASTRO_IMAGE_IMPORT_Z221WHd from "../../assets/images/website.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F01-website.json";
import __ASTRO_IMAGE_IMPORT_ZKkhqq from "../../assets/images/github.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F03-github.json";
import __ASTRO_IMAGE_IMPORT_1dEdfH from "../../assets/images/intheloop.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F05-intheloop.json";
import __ASTRO_IMAGE_IMPORT_Zhbk6e from "../../assets/images/tapped.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F04-tapped.json";
import __ASTRO_IMAGE_IMPORT_2a2d9A from "../../assets/images/housefly.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F06-housefly.json";
import __ASTRO_IMAGE_IMPORT_ZWwP1v from "../../assets/images/moments-fm.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F07-moments.json";
import __ASTRO_IMAGE_IMPORT_64aFv from "../../assets/images/languagehub.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F09-languagehub.json";
import __ASTRO_IMAGE_IMPORT_1Gr3u3 from "../../assets/images/playstore.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F10-apps.json";
import __ASTRO_IMAGE_IMPORT_1Ikq47 from "../../assets/images/saintjohn.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F08-saintjohn.json";
import __ASTRO_IMAGE_IMPORT_1g3GXR from "../../assets/images/twitter.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F11-twitter.json";
import __ASTRO_IMAGE_IMPORT_1Li0xS from "../../assets/images/linkedin.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F12-linkedin.json";
import __ASTRO_IMAGE_IMPORT_1jtpP3 from "../../assets/images/telegram.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F13-telegram.json";
export default new Map([["../../assets/images/blog.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F02-blog.json", __ASTRO_IMAGE_IMPORT_ZuwFOt], ["../../assets/images/website.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F01-website.json", __ASTRO_IMAGE_IMPORT_Z221WHd], ["../../assets/images/github.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F03-github.json", __ASTRO_IMAGE_IMPORT_ZKkhqq], ["../../assets/images/intheloop.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F05-intheloop.json", __ASTRO_IMAGE_IMPORT_1dEdfH], ["../../assets/images/tapped.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F04-tapped.json", __ASTRO_IMAGE_IMPORT_Zhbk6e], ["../../assets/images/housefly.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F06-housefly.json", __ASTRO_IMAGE_IMPORT_2a2d9A], ["../../assets/images/moments-fm.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F07-moments.json", __ASTRO_IMAGE_IMPORT_ZWwP1v], ["../../assets/images/languagehub.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F09-languagehub.json", __ASTRO_IMAGE_IMPORT_64aFv], ["../../assets/images/playstore.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F10-apps.json", __ASTRO_IMAGE_IMPORT_1Gr3u3], ["../../assets/images/saintjohn.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F08-saintjohn.json", __ASTRO_IMAGE_IMPORT_1Ikq47], ["../../assets/images/twitter.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F11-twitter.json", __ASTRO_IMAGE_IMPORT_1g3GXR], ["../../assets/images/linkedin.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F12-linkedin.json", __ASTRO_IMAGE_IMPORT_1Li0xS], ["../../assets/images/telegram.png?astroContentImageFlag=&importer=src%2Fcontent%2Flinks%2F13-telegram.json", __ASTRO_IMAGE_IMPORT_1jtpP3]]);
		