name = "saint-john-website"
compatibility_date = "2025-03-15"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"

[[routes]]
pattern = "saintjohn.jonaylor.com"
custom_domain = true

